name = "NeuralODELM"
uuid = "12345678-abcd-4abc-9def-1234567890ab"
authors = ["Zayd Bashir <you@example.com>"]
version = "0.1.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
DiffEqFlux = "aae7a2af-3d4f-5e19-a356-7da93b79d9d0"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

